package com.tiktok.interactionservice.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Identifies one playback of one video, generated by the client when playback starts and thrown
 * away when it ends. The server cannot derive this: two requests from the same viewer for the
 * same video are indistinguishable otherwise, and the difference between "the player retried a
 * request whose response was lost" and "the viewer played it again" is exactly what the view
 * count turns on.
 *
 * @param playId opaque to the server; a UUID in practice. Bounded in length only because it is
 *               untrusted input that becomes part of a Redis key.
 */
public record ViewRequest(
        @NotBlank @Size(max = 64) String playId
) {
}
